### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by HappyCoderGS** [reeuq/DS_SDP_CNN_MIL#1]
你好，这是基于卷积神经网络的多示例学习吧，这是应用到文本还是图像呢？谢谢

**Comment by reeuq** [comment]
是的，应用到文本处理中的

**Comment by HappyCoderGS** [comment]
> 是的，应用到文本处理中的
谢谢您的回复。
我最近在研究怎么把卷积神经网络应用到多示例学习的问题上，请您指点指点，我主要做图像方面的，还没找到能跑通的代码，方便的话加个微信或者QQ，我的QQ493412979.

**Comment by reeuq** [comment]
> > 是的，应用到文本处理中的
> > 谢谢您的回复。
> > 我最近在研究怎么把卷积神经网络应用到多示例学习的问题上，请您指点指点，我主要做图像方面的，还没找到能跑通的代码，方便的话加个微信或者QQ，我的QQ493412979.

基于theano的CNN+MIL的文本处理代码如下：
https://github.com/smilelhh/ds_pcnns

基于pytorch的CNN+MIL的文本处理代码如下：
https://github.com/ShomyLiu/pytorch-relation-extraction

在这两个项目的README中均有详细的说明，代码也不是很多，可以看看

**Comment by HappyCoderGS** [comment]
> > > 是的，应用到文本处理中的
> > > 谢谢您的回复。
> > > 我最近在研究怎么把卷积神经网络应用到多示例学习的问题上，请您指点指点，我主要做图像方面的，还没找到能跑通的代码，方便的话加个微信或者QQ，我的QQ493412979.
> 
> 基于theano的CNN+MIL的文本处理代码如下：
> https://github.com/smilelhh/ds_pcnns
> 
> 基于pytorch的CNN+MIL的文本处理代码如下：
> https://github.com/ShomyLiu/pytorch-relation-extraction
> 
> 在这两个项目的README中均有详细的说明，代码也不是很多，可以看看

非常谢谢您
